fix(dav): use of webdav library
nextcloud-libraries/nextcloud-files pull request #821
Opened 2023-10-30 18:09 UTC by pulsejet

https://github.com/nextcloud/server/pull/41202

2023-10-30 18:09 UTC, pulsejet commented
BTW I can't push to this repo for some reason so had to fork

2023-10-31 08:30 UTC, skjnldsv commented
> Reference in new issue

Sorry, forgot to add you to the right group.
We selectively give stricter permission on this org

2023-10-31 08:31 UTC, skjnldsv requested changes
Please fix eslint :)

2023-10-31 19:27 UTC, skjnldsv approved these changes

2023-11-08 11:11 UTC, merged