fix(Node): Do not drop readonly attributes but only forbid updating them
nextcloud-libraries/nextcloud-files pull request #967
Opened 2024-05-29 08:08 UTC by susnux

Attributes that are readonly should still be listed in the `attributes` getter, otherwise this is a hard breaking change as a lot of apps already depend on `attributes`. So instead only ensure that readonly attributes are skipped by the proxy handler.

2024-05-29 08:14 UTC, susnux commented
See error when upgrading files on server (and we need to backport to 29 and 28!):
https://github.com/nextcloud/server/pull/45538

2024-05-29 15:26 UTC, skjnldsv requested changes
I disagree, why do you use the `attributes.size` ?
That is the issue in the first place, no?

2024-05-29 15:32 UTC, susnux commented
> I disagree, why do you use the attributes.size ?
> That is the issue in the first place, no?

It was never documented to not use attributes for `size` or `basename` so removing them from attributes breaks the API.
So removing attributes was a breaking change that needs to be reverted or like here to be fixed.

2024-05-29 16:47 UTC, susnux commented
Added a test case to prevent doing:
```js
file.attributes.owner = 'foo'
```

As this is also protected

2024-05-29 16:48 UTC, merged

2024-06-04 08:02 UTC, skjnldsv commented on lib/files/node.ts
> +				throw e
One drawback of this, now there is no way to update ll attributes without updating the mtime :/
That was one of the feature I added and needed from https://github.com/nextcloud-libraries/nextcloud-files/pull/947 :sweat_smile: @susnux

2024-06-04 08:02 UTC, skjnldsv commented on lib/files/node.ts
> +				throw e
Also, you can't remove attributes anymore (unless you know they exist on the node already)

2024-06-04 08:17 UTC, skjnldsv commented on lib/files/node.ts
> +				throw e
https://github.com/nextcloud-libraries/nextcloud-files/pull/973